### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by pp00704831** [xuboming8/DSTNet#1]
Hello,

Congratulations on your CVPR paper!
I have a question regarding testing on the GoPro test set.
I have been using the default settings (30 frames), but I encountered a CUDA out-of-memory error when testing on a 3090 or V100 GPU.
Can I test one a 3090 or V100 GPU?

**Comment by xuboming8** [comment]
All experimental results are tested on A6000(48G). If you need to test on 3090 or V100, you can reduce the number of frames during testing.
