### ISSUE TITLE
the overall directory structure of the project

### ISSUE THREAD

**Issue by Plus-Ultar** [xuboming8/DSTNet#2]
Hello, sorry to bother you. Can you explain the overall directory structure of the project, I am confused about where the dataset is placed.

**Comment by xuboming8** [comment]
We follow the framework of basicsr, you can put dataset in any location according to your needs, just need to modify the root of your dataset in yaml(dataroot_gt，dataroot_lq).

**Comment by Plus-Ultar** [comment]
Thank you for answering.I have another question.Can you upload the dataset you used, I found that the dataset (GOPRO) structure used in the project is very different from the original dataset.

**Comment by xuboming8** [comment]
You need to change the naming format of GOPRO dataset from 000000.png to 000xxx.png.
